question_data = [
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Science: Computers",
         "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "medium",
         "category": "Science: Computers",
         "question": "The first dual-core CPU was the Intel Pentium D.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Time on Computers is measured via the EPOX System.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a "
                     "Harvard Mark II computer.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;"
                     "JavaScript&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "To bypass US Munitions Export Laws, the creator of the PGP "
                     "published all the source code in book form. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
         "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Science: Computers",
         "question": "The Python programming language gets its name from the British comedy group &quot;"
                     "Monty Python.&quot;",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}
    ]

